# snippets is the base configuration directory for all child configurations
# this is a complete Panorama and reference device-group and template stack configuration
# this is based on a 'shared model' with all device-group elements in Shared
# this is based on a 'shared model' with all template elements in the 'iron-skillet' template

# snippet folder name
name: skillet_panorama_v80
# label used for menu selection
label: v8.0 Iron-Skillet for Panorama (Shared Values)
description: Iron-Skillet baseline configuration for Panorama with device-group and stack specific values
# type of device configuration
type: panorama
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet
  collection:
    - IronSkillet

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: PANORAMA_TYPE
    description: Panorama management IP type
    default: static
    type_hint: dropdown
    dd_list:
      - key: static
        value: static
      - key: cloud dhcp
        value: cloud
  - name: PANORAMA_NAME
    description: Panorama hostname
    default: panorama01
    type_hint: text
  - name: PANORAMA_IP
    description: Panorama IP
    default: 192.168.55.7
    type_hint: ip_address
  - name: PANORAMA_MASK
    description: Panorama netmask
    default: 255.255.255.0
    type_hint: ip_address
  - name: PANORAMA_DG
    description: Panorama default gateway
    default: 192.168.55.2
    type_hint: ip_address
  - name: CONFIG_EXPORT_IP
    description: IP address for scheduled config exports
    default: 192.0.2.3
    type_hint: text
  - name: TEMPLATE
    description: Template name for the managed device
    default: sample_template
    type_hint: text
  - name: STACK
    description: Template stack name for Panorama
    default: sample_stack
    type_hint: text
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    default: sample_devicegroup
    type_hint: text
  - name: FW_NAME
    description: Device Name for NGFW
    default: sample
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
  - name: NTP_1
    description: Network Time Protocol Server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: Network Time Protocol Server 2
    default: 1.pool.ntp.org
    type_hint: text
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: password
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: ip_address
  - name: SINKHOLE_IPV4
    description: sinkhole address IPv4
    default: 72.5.65.111
    type_hint: ip_address
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
  - name: INTERNET_ZONE
    description: untrust zone to filter out in reports
    default: internet
    type_hint: text
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text
# option built into the templates to ignore the panw published external dynamic lists security rules
# should ONLY be excluded based on licensing limitations outside of best practices
# when 'yes' (default) will include the EDL rule
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists security rules
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: panorama_system
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: panorama_system.xml
  - name: panorama_setting
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
    file: panorama_setting.xml
  - name: panorama_log_settings
    xpath: /config/panorama/log-settings
    file: panorama_log_settings.xml
  - name: log_collector_group
    xpath: /config/devices/entry[@name='localhost.localdomain']/log-collector-group
    file: log_collector_group.xml
  - name: shared_tag
    xpath: /config/shared/tag
    file: tag.xml
  - name: template
    xpath: /config/devices/entry[@name='localhost.localdomain']/template
    file: template.xml
  - name: device_system_shared
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system_shared.xml
  - name: device_setting
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
    file: device_setting.xml
  - name: device_mgt_config
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/mgt-config
    file: device_mgt_config.xml
  - name: shared_log_settings
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/shared/log-settings
    file: shared_log_settings.xml
  - name: zone_protection_profile
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
    file: zone_protection_profile.xml
  - name: shared_address
    xpath: /config/shared/address
    file: address.xml
  - name: shared_external_list
    xpath: /config/shared/external-list
    file: external_list.xml
  - name: shared_log_profiles
    xpath: /config/shared/log-settings/profiles
    file: log_settings_profiles.xml
  - name: shared_profiles_custom_url_category
    xpath: /config/shared/profiles/custom-url-category
    file: profiles_custom_url_category.xml
  - name: profiles_decryption
    xpath: /config/shared/profiles/decryption
    file: profiles_decryption.xml
  - name: profiles_virus
    xpath: /config/shared/profiles/virus
    file: profiles_virus.xml
  - name: profiles_spyware
    xpath: /config/shared/profiles/spyware
    file: profiles_spyware.xml
  - name: profiles_vulnerability
    xpath: /config/shared/profiles/vulnerability
    file: profiles_vulnerability.xml
  - name: profiles_file_blocking
    xpath: /config/shared/profiles/file-blocking
    file: profiles_file_blocking.xml
  - name: profiles_url_filtering
    xpath: /config/shared/profiles/url-filtering
    file: profiles_url_filtering.xml
  - name: profiles_wildfire_analysis
    xpath: /config/shared/profiles/wildfire-analysis
    file: profiles_wildfire_analysis.xml
  - name: profile_group
    xpath: /config/shared/profile-group
    file: profile_group.xml
  - name: post_rulebase_default_security_rules
    xpath: /config/shared/post-rulebase/default-security-rules
    file: post_rulebase_default_security_rules.xml
  - name: pre_rulebase_security
    xpath: /config/shared/pre-rulebase/security
    file: pre_rulebase_security.xml
  - name: post_rulebase_decryption
    xpath: /config/shared/post-rulebase/decryption
    file: post_rulebase_decryption.xml
  - name: pre_rulebase_decryption
    xpath: /config/shared/pre-rulebase/decryption
    file: pre_rulebase_decryption.xml
  - name: stack
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack
    file: template_stack.xml
  - name: device_system_local
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ TEMPLATE }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system_local.xml
  - name: devicegroup
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group
    file: device_group.xml
  - name: reports
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/reports
    file: reports_simple.xml
  - name: report_group_simple
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/report-group
    file: report_group_simple.xml
  - name: email_scheduler
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/email-scheduler
    file: email_scheduler_simple.xml

quick_groups:
  security_profiles:
    - shared_profiles_custom_url_category
    - profiles_decryption
    - profiles_virus
    - profiles_spyware
    - profiles_vulnerability
    - profiles_file_blocking
    - profiles_url_filtering
    - profiles_wildfire_analysis
    - profile_group
  objects:
    - shared_tag
    - shared_address
    - shared_external_list