# xpaths as python dictionary with name as a key
# %(text)s variables showing xpath variables - python substitution

xpaths_list = { 
      "profile_group": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/profile-group/entry[@name='%(profile_group)s']",
      "profile_group_all": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/profile-group",
      "profile_group_zone": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/profile-group",
      "device_group": "/config/devices/entry[@name='localhost.localdomain']/device-group",
      "profile": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/profiles/%(profile)s",
      "service": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/service",
      "nat": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/post-rulebase/nat",
      "log_profile": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/log-settings/profiles",
      "security_rules": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/post-rulebase/security",
      "security_rules_post": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/post-rulebase/security",
      "security_rules_pre": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/pre-rulebase/security",
      "default_security_rules": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/post-rulebase/default-security-rules",
      "update_schedule": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule",
      "template": "/config/devices/entry[@name='localhost.localdomain']/template",
      "template-stack": "/config/devices/entry[@name='localhost.localdomain']/template-stack",
      "log_settings": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/shared/log-settings",
      "interface": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/interface",
      "network_profiles": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/profiles",
      "virtual_router": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/virtual-router",
      "zone": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone",
      "import": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/import",
      "wildfire": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire",
      "server": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/dhcp/interface/entry[@name='%(port)s']/server",
      "ntp-servers": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ntp-servers",
      "decryption_rules_pre": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/pre-rulebase/decryption", 
      "route_service": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/route/service/entry[@name='%(route_service)s']",
      "group_mapping": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/group-mapping",
      "userid_agent": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/user-id-agent",
      "server_profile": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/shared/server-profile",
      "ike_gateway": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/ike",
      "ipsec_tunnel": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/tunnel",
      "shared_tag": "/config/shared/tag",
      "shared_profile": "/config/shared/profiles",
      "shared_logging": "/config/shared/log-settings",
      "service_connection": "/config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/service-connection",
      "trusted-zone": "/config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/remote-networks/trusted-zones",
      "onboarding": "/config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/remote-networks/onboarding",
      "address": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/address",
      "tag": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/tag",
      "external_list": "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='%(devicegroup)s']/external-list",
      "zone_protection_profile": "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='%(pan_template)s']/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile",
            }