name: validate-IronSkillet-v91-panos-bae945bc-c667-4e56-a3fc-73bbb5afbe0g
label: IronSkillet - check NGFW config for updated v9.2 elements

description: |
  Check NGFW for new items updated in IronSkillet v9.x skillet

type: pan_validation
labels:
  collection:
    - IronSkillet
    - Validation

variables:

snippets:

  - name: rules
    cmd: parse
    variable: config
    outputs:
      - name: security_rule
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
      - name: security_rule_outbound_edl
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules/entry[@name='Outbound Block Rule']
      - name: security_rule_inbound_edl
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules/entry[@name='Inbound Block Rule']
      - name: device_setting
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
      - name: wf_limit_script
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire/file-size-limit/entry[@name='script']
      - name: as_profiles_outbound_dns
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/spyware/entry[@name='Outbound-AS']/botnet-domains/lists
      - name: url_profile_outbound
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry[@name='Outbound-URL']
      - name: address
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address/entry[@name='Sinkhole-IPv4']

  - name: security_rules_outbound_edl
    label: IronSkillet outbound EDL block rule destination includes panw-bulletproof-ip-list
    test: security_rule_outbound_edl | element_value_contains('destination.member', 'panw-bulletproof-ip-list')
    fail_message: IronSkillet EDL block rules should include the EDL panw-bulletproof-ip-list
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#ironskillet-security-policies

  - name: security_rules_inbound_edl
    label: IronSkillet inbound EDL block rule source includes panw-bulletproof-ip-list
    test: security_rule_inbound_edl | element_value_contains('source.member', 'panw-bulletproof-ip-list')
    fail_message: IronSkillet EDL block rules should include the EDL panw-bulletproof-ip-list
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#ironskillet-security-policies

  - name: api_key_lifetime
    label: api key lifetime is configured
    test: device_setting | tag_present('management.api.key.lifetime')
    fail_messasge: |
      set to a non-zero value to periodically force a key value update
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#device-setup-management-authentication-settings

  - name: wf_new_type_limits
    when: device_setting | tag_present('wildfire.file-size-limit')
    label: new WF type script file size limit configured as 2000
    test: wf_limit_script | element_value('size-limit') == '2000'
    fail_message: newer script file types have been added for wildfire analysis but recommended sizes have not been configured.
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#device-setup-wildfire-general-settings

  - name: address_fqdn
    label: IPv4 sinkhole address object set to FQDN
    test: address | tag_present('fqdn')
    fail_message: the address object type for the ipv4 sinkhole address should be updated as fqdn and not ip
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#ironskillet-address-objects

  - name: as_profile_check
    label: DNS Security Service sinkhole is configured
    test: as_profiles_outbound_dns | attribute_present('entry', 'name', 'default-paloalto-cloud')
    fail_message: the anti-spyware dns configuration should include the new dns security service using default-paloalto-cloud
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#anti-spyware

  - name: url_new_domain
    label: the newly-registred-domain URL category is set to alert
    test: url_profile_outbound | element_value_contains('alert.member', 'newly-registered-domain')
    fail_message: URL category newly-registered-domain should be set to alert for logging visibility
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#url-filtering

  - name: url_new_domain_grayware
    label: the grayware URL category set to block
    test: url_profile_outbound | element_value_contains('block.member', 'grayware')
    fail_message: URL category grayware should be set to block
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#url-filtering

