# xpaths as python dictionary with name as a key

xpaths_panos = {
    "address": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address",
    "decryption_rules": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/decryption",
    "default_security_rules": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/default-security-rules",
    "device_setting": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting",
    "device_system": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system",
    "dhcp_server": "TBD",
    "email_scheduler": "TBD",
    "external_list": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list",
    "ike_gateway": "/config/devices/entry[@name='localhost.localdomain']/network/ike",
    "interface": "/config/devices/entry[@name='localhost.localdomain']/network/interface",
    "ipsec_tunnel": "/config/devices/entry[@name='localhost.localdomain']/network/tunnel",
    "log_settings": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings",
    "log_settings_profiles": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles",
    "nat": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat",
    "network_profiles": "/config/devices/entry[@name='localhost.localdomain']/network/profiles",
    "ntp_servers": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ntp-servers",
    "profile_group": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group",
    "profiles_custom_url_category": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/custom-url-category",
    "profiles_decryption": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/decryption",
    "profiles_file_blocking": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/file-blocking",
    "profiles_spyware": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/spyware",
    "profiles_url_filtering": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering",
    "profiles_virus": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus",
    "profiles_vulnerability": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability",
    "profiles_wildfire_analysis": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/wildfire-analysis",
    "reports": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/reports",
    "report_group": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/report-group",
    "route_service": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/route/service/entry[@name='{{ ROUTE_SERVICE }}']",
    "security_rules": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security",
    "server_profile": "/config/shared/server-profile",
    "service": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/service",
    "shared_email_scheduler": "/config/shared/email-scheduler",
    "shared_log_settings": "/config/shared/log-settings",
    "shared_log_settings_profiles": "/config/shared/log-settings/profiles",
    "shared_reports": "/config/shared/reports",
    "shared_report_group": "/config/shared/report-group",
    "tag": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag",
    "update_schedule": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule",
    "userid_agent": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/user-id-agent",
    "userid_group_mapping": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/group-mapping",
    "virtual_router": "/config/devices/entry[@name='localhost.localdomain']/network/virtual-router",
    "wildfire": "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire",
    "zone": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone",
    "zone_import_interface": "/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/import",
    "zone_protection_profile": "/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile",
}

