# panos shared log settings configuration snippets

name: panos_ngfw_shared_log_settings_email_profile_10_0
label: PAN_OS NGFW Shared Log Settings - Email Profile
description: |-
    reference shared log settings email profile configuration snippets
type: panos
labels:
    collection:
      - IronSkillet 10.0 PAN-OS Snippets

variables:

  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles

snippets:

-   name: ironskillet_shared_log_settings_email_profile
    xpath: /config/shared/log-settings
    element: |-
      <email>
        <entry name="Sample_Email_Profile">
          <server>
            <entry name="Sample_Email_Profile">
              <display-name>Threat_Alerts</display-name>
              <gateway>{{ EMAIL_PROFILE_GATEWAY }}</gateway>
              <from>{{ EMAIL_PROFILE_FROM }}</from>
              <to>{{ EMAIL_PROFILE_TO }}</to>
              <protocol>SMTP</protocol>
            </entry>
          </server>
        </entry>
      </email>